name: Build

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: pdm-project/setup-pdm@v3
      - name: Install dependencies
        run: pdm install
      - name: Build
        run: pdm run app build --clean --cname ipa.xiaoyustudio.com
      - name: Upload OSS
        run: pdm run app upload
        env:
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      - name: Push to branch
        run: |
            git config --local user.email "github-actions@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            cp -r .git dist
            cd dist
            git checkout --orphan static-pages
            git add -A
            git commit -m "Auto update at $(date -u '+%Y-%m-%d %H:%M:%S %Z')"
            git push -f -u origin static-pages
